# Generated by Django 4.1.1 on 2022-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedYoutubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_video_id', models.CharField(db_index=True, max_length=15)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField()),
                ('published_on', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
        migrations.AddIndex(
            model_name='fetchedyoutubedata',
            index=models.Index(fields=['title', 'unique_video_id'], name='main_fetche_title_16a50d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fetchedyoutubedata',
            unique_together={('unique_video_id', 'title', 'thumbnail_url')},
        ),
    ]
